[package]
name = "try_from_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
try_from_derive_proc = { version = "0.1", path = "ProcMacros" }

[dev-dependencies]
strum_macros = "0.22"

[workspace]
members = ["ProcMacros"]
